/*
 * SPDX-FileCopyrightText: syuilo and misskey-project
 * SPDX-License-Identifier: AGPL-3.0-only
 */

import { Module } from '@nestjs/common';
import type { Provider } from '@nestjs/common';
import type { DataSource, EntityTarget, ObjectLiteral, Repository } from 'typeorm';
import { DI } from '@/di-symbols.js';
import { TenantRuntimeService } from '@/core/TenantRuntimeService.js';
import {
	MiAbuseReportNotificationRecipient,
	MiAbuseUserReport,
	MiAccessToken,
	MiAd,
	MiAnnouncement,
	MiAnnouncementRead,
	MiAntenna,
	MiApp,
	MiAuthSession,
	MiAvatarDecoration,
	MiBlocking,
	MiBubbleGameRecord,
	MiChannel,
	MiChannelFavorite,
	MiChannelFollowing,
	MiChannelMuting,
	MiChatApproval,
	MiChatMessage,
	MiChatRoom,
	MiChatRoomInvitation,
	MiChatRoomMembership,
	MiClip,
	MiClipFavorite,
	MiClipNote,
	MiDriveFile,
	MiDriveFolder,
	MiEmoji,
	MiEmojiRequest,
	MiFlash,
	MiFlashLike,
	MiFollowing,
	MiFollowRequest,
	MiGalleryLike,
	MiGalleryPost,
	MiHashtag,
	MiInboxRule,
	MiInstance,
	MiMeta,
	MiModerationLog,
	MiMuting,
	MiNote,
	MiNoteDraft,
	MiNoteFavorite,
	MiNoteReaction,
	MiNoteThreadMuting,
	MiPage,
	MiPageLike,
	MiPasswordResetRequest,
	MiPoll,
	MiPollVote,
	MiPromoNote,
	MiPromoRead,
	MiRegistrationTicket,
	MiRegistryItem,
	MiRelay,
	MiRenoteMuting,
	type MiRepository,
	miRepository,
	MiRetentionAggregation,
	MiReversiGame,
	MiRole,
	MiRoleAssignment,
	MiSignin,
	MiSwSubscription,
	MiSystemAccount,
	MiSystemWebhook,
	MiUsedUsername,
	MiUser,
	MiUserIp,
	MiUserKeypair,
	MiUserList,
	MiUserListFavorite,
	MiUserListMembership,
	MiUserMemo,
	MiUserNotePining,
	MiUserPending,
	MiUserProfile,
	MiUserPublickey,
	MiUserSecurityKey,
	MiWebhook,
	MiEvent,
} from './_.js';

function createRepositoryProxy<T extends ObjectLiteral>(runtime: TenantRuntimeService, target: EntityTarget<T>, extend = true): Repository<T> {
	return new Proxy({} as Repository<T>, {
		get(_target, property, receiver) {
			const repository = runtime.getCurrentDb().getRepository(target);
			const actual = extend ? repository.extend(miRepository as MiRepository<T>) : repository;
			const value = Reflect.get(actual, property, receiver);
			return typeof value === 'function' ? value.bind(actual) : value;
		},
	});
}

function repositoryProvider(symbol: symbol, model: EntityTarget<any>, extend = true): Provider {
	return {
		provide: symbol,
		useFactory: (runtime: TenantRuntimeService) => createRepositoryProxy(runtime, model, extend),
		inject: [TenantRuntimeService],
	};
}

const providers = [
	repositoryProvider(DI.inboxRuleRepository, MiInboxRule, false),
	repositoryProvider(DI.usersRepository, MiUser),
	repositoryProvider(DI.notesRepository, MiNote),
	repositoryProvider(DI.announcementsRepository, MiAnnouncement),
	repositoryProvider(DI.announcementReadsRepository, MiAnnouncementRead),
	repositoryProvider(DI.appsRepository, MiApp),
	repositoryProvider(DI.avatarDecorationsRepository, MiAvatarDecoration),
	repositoryProvider(DI.noteFavoritesRepository, MiNoteFavorite),
	repositoryProvider(DI.noteThreadMutingsRepository, MiNoteThreadMuting),
	repositoryProvider(DI.noteReactionsRepository, MiNoteReaction),
	repositoryProvider(DI.noteDraftsRepository, MiNoteDraft),
	repositoryProvider(DI.pollsRepository, MiPoll),
	repositoryProvider(DI.pollVotesRepository, MiPollVote),
	repositoryProvider(DI.userProfilesRepository, MiUserProfile),
	repositoryProvider(DI.userKeypairsRepository, MiUserKeypair),
	repositoryProvider(DI.userPendingsRepository, MiUserPending),
	repositoryProvider(DI.userSecurityKeysRepository, MiUserSecurityKey),
	repositoryProvider(DI.userPublickeysRepository, MiUserPublickey),
	repositoryProvider(DI.userListsRepository, MiUserList),
	repositoryProvider(DI.userListFavoritesRepository, MiUserListFavorite),
	repositoryProvider(DI.userListMembershipsRepository, MiUserListMembership),
	repositoryProvider(DI.userNotePiningsRepository, MiUserNotePining),
	repositoryProvider(DI.userIpsRepository, MiUserIp),
	repositoryProvider(DI.usedUsernamesRepository, MiUsedUsername),
	repositoryProvider(DI.followingsRepository, MiFollowing),
	repositoryProvider(DI.followRequestsRepository, MiFollowRequest),
	repositoryProvider(DI.instancesRepository, MiInstance),
	repositoryProvider(DI.emojisRepository, MiEmoji),
	repositoryProvider(DI.emojiRequestsRepository, MiEmojiRequest),
	repositoryProvider(DI.driveFilesRepository, MiDriveFile),
	repositoryProvider(DI.driveFoldersRepository, MiDriveFolder),
	repositoryProvider(DI.metasRepository, MiMeta),
	repositoryProvider(DI.mutingsRepository, MiMuting),
	repositoryProvider(DI.renoteMutingsRepository, MiRenoteMuting),
	repositoryProvider(DI.blockingsRepository, MiBlocking),
	repositoryProvider(DI.swSubscriptionsRepository, MiSwSubscription),
	repositoryProvider(DI.systemAccountsRepository, MiSystemAccount),
	repositoryProvider(DI.hashtagsRepository, MiHashtag),
	repositoryProvider(DI.abuseUserReportsRepository, MiAbuseUserReport),
	repositoryProvider(DI.abuseReportNotificationRecipientRepository, MiAbuseReportNotificationRecipient),
	repositoryProvider(DI.registrationTicketsRepository, MiRegistrationTicket),
	repositoryProvider(DI.authSessionsRepository, MiAuthSession),
	repositoryProvider(DI.accessTokensRepository, MiAccessToken),
	repositoryProvider(DI.signinsRepository, MiSignin),
	repositoryProvider(DI.pagesRepository, MiPage),
	repositoryProvider(DI.pageLikesRepository, MiPageLike),
	repositoryProvider(DI.galleryPostsRepository, MiGalleryPost),
	repositoryProvider(DI.galleryLikesRepository, MiGalleryLike),
	repositoryProvider(DI.moderationLogsRepository, MiModerationLog),
	repositoryProvider(DI.clipsRepository, MiClip),
	repositoryProvider(DI.clipNotesRepository, MiClipNote),
	repositoryProvider(DI.clipFavoritesRepository, MiClipFavorite),
	repositoryProvider(DI.antennasRepository, MiAntenna),
	repositoryProvider(DI.promoNotesRepository, MiPromoNote),
	repositoryProvider(DI.promoReadsRepository, MiPromoRead),
	repositoryProvider(DI.relaysRepository, MiRelay),
	repositoryProvider(DI.channelsRepository, MiChannel),
	repositoryProvider(DI.channelFollowingsRepository, MiChannelFollowing),
	repositoryProvider(DI.channelFavoritesRepository, MiChannelFavorite),
	repositoryProvider(DI.channelMutingRepository, MiChannelMuting),
	repositoryProvider(DI.registryItemsRepository, MiRegistryItem),
	repositoryProvider(DI.webhooksRepository, MiWebhook),
	repositoryProvider(DI.systemWebhooksRepository, MiSystemWebhook),
	repositoryProvider(DI.adsRepository, MiAd),
	repositoryProvider(DI.passwordResetRequestsRepository, MiPasswordResetRequest),
	repositoryProvider(DI.retentionAggregationsRepository, MiRetentionAggregation),
	repositoryProvider(DI.rolesRepository, MiRole),
	repositoryProvider(DI.roleAssignmentsRepository, MiRoleAssignment),
	repositoryProvider(DI.flashsRepository, MiFlash),
	repositoryProvider(DI.flashLikesRepository, MiFlashLike),
	repositoryProvider(DI.userMemosRepository, MiUserMemo),
	repositoryProvider(DI.chatMessagesRepository, MiChatMessage),
	repositoryProvider(DI.chatRoomsRepository, MiChatRoom),
	repositoryProvider(DI.chatRoomMembershipsRepository, MiChatRoomMembership),
	repositoryProvider(DI.chatRoomInvitationsRepository, MiChatRoomInvitation),
	repositoryProvider(DI.chatApprovalsRepository, MiChatApproval),
	repositoryProvider(DI.bubbleGameRecordsRepository, MiBubbleGameRecord),
	repositoryProvider(DI.reversiGamesRepository, MiReversiGame),
];

const $eventsRepository: Provider = {
	provide: DI.eventsRepository,
	useFactory: (db: DataSource) => db.getRepository(MiEvent).extend(miRepository as MiRepository<MiEvent>),
	inject: [DI.db],
};

@Module({
	imports: [],
	providers: [...providers, $eventsRepository],
	exports: [...providers, $eventsRepository],
})
export class RepositoryModule {}
